import type { AiGenerationStyle } from "./types";

export interface GenerationPromptStage {
  id: string;
  label: string;
  prompt: () => string;
}

export interface GenerationStyleConfig {
  id: AiGenerationStyle;
  label: string;
  maxColors: number;
  stages: GenerationPromptStage[];
}

export interface ResolvedGenerationPromptStage {
  id: string;
  label: string;
  prompt: string;
}

const flatCartoonPrompt: GenerationPromptStage["prompt"] = () => [
  "Create a controlled flat-cartoon reconstruction of the same individual pet in the reference image.",
  "",
  "This is an intermediate design for later conversion into coarse pixel art and a physical fuse-bead pattern. Preserve identity and anatomy first, then simplify only detail that will not survive that conversion.",
  "",
  "SUBJECT AND COMPOSITION",
  "",
  "Show only the complete head and both ears. Exclude the neck, chest, body, collar, accessories, hands, scenery, and unrelated objects.",
  "",
  "Create a centered, upright portrait with the face looking toward the viewer. Correct head tilt, roll, yaw, and ordinary photographic perspective so the portrait reads as a stable front-facing design. When the reference is oblique or partly occluded, reconstruct a front-facing view from the visible evidence while avoiding invented decorative details.",
  "",
  "Keep the head and ear scale, spacing, and overall proportions faithful to this individual pet.",
  "",
  "IDENTITY AND STRUCTURAL PRIORITY",
  "",
  "Preserve the features that define the individual: head silhouette, ear shape, ear placement, eye size and spacing, eye color, nose and muzzle structure, jaw and chin shape, dominant fur colors, major facial color regions, and distinctive markings.",
  "",
  "Resolve the main head axis and overall silhouette with near-bilateral balance, but do not mirror the design. Keep meaningful asymmetry in markings, fur color boundaries, eyes, ears, and other identity features.",
  "",
  "Preserve local anatomical structure before applying graphic simplification. The chin, cheeks, muzzle, jaw, forehead, ears, and eye surrounds must retain their characteristic bends and proportions. Do not replace a structurally distinctive contour with a generic circle, oval, triangle, or other primitive merely because it is easier to draw.",
  "",
  "Do not beautify, idealize, enlarge the eyes, regularize the ears, or redesign the pet as a generic animal.",
  "",
  "CONTROLLED FLAT SIMPLIFICATION",
  "",
  "Simplify in layers: remove photographic lighting, texture, individual hairs, tiny edge noise, and non-identifying fragments first; simplify major anatomy and markings only when their structure and identity remain clear.",
  "",
  "Use clean connected color regions with boundaries that follow the natural structure of the head. Use broad curves and a small number of deliberate contour changes, but retain meaningful concavities, corners, tapers, and transitions in the silhouette.",
  "",
  "Keep the outer silhouette calm and visually balanced without forcing every internal feature to be symmetrical. Large regions should remain connected where they represent one visual feature, while important small regions may remain separate.",
  "",
  "Do not make the image more geometric or abstract than necessary. The result should read as a simplified illustration of this pet, not as a collection of generic geometric icons.",
  "",
  "COLOR AND FLAT RENDERING",
  "",
  "Use approximately 8 to 12 purposeful solid colors when possible. Do not merge an eye, nose, inner ear, marking, or meaningful neutral fur region solely to meet a lower color count. Every retained color must serve a recognizable feature or a necessary separation between adjacent regions.",
  "",
  "Use uniform flat colors with no gradients, soft transitions, shadows, reflected light, transparency, texture, or artificial depth cues. Ignore photographic illumination and represent intrinsic local colors.",
  "",
  "Match the reference image's hue, relative lightness, saturation, and warm or cool balance. Preserve cool silver gray, blue-gray, warm gray, and other neutral fur colors as they appear. Do not shift gray fur toward beige, brown, or yellow.",
  "",
  "Keep distinctive colors such as the eyes, nose, inner ears, and important markings close to the reference. Do not globally increase or reduce saturation. Preserve vivid colors where they exist and keep muted colors muted.",
  "",
  "FACIAL FEATURES AND THIN DETAILS",
  "",
  "Simplify the eyes, nose, mouth, and muzzle into a few clean regions while preserving their size, spacing, position, shape, and color. A single simple eye highlight may remain when it is visually important.",
  "",
  "Slightly thicken an important thin marking or facial feature only when needed for later pixelization. Remove non-identifying thin detail instead of introducing fine texture or a smaller visual scale.",
  "",
  "BACKGROUND AND OUTPUT",
  "",
  "Use one uniform solid technical background color that clearly separates the pet from the background. Do not add scenery, decoration, texture, gradient, shadow, or an artificial outer outline.",
  "",
  "Output the same individual pet as a clean flat-cartoon portrait: upright, front-facing, structurally faithful, calmly balanced in its outer silhouette, and simplified enough for later pixelization.",
  "",
  "Do not generate pixel art or a visible pixel grid in this stage.",
].join("\n");

const pixelArtPrompt: GenerationPromptStage["prompt"] = () => [
  "Convert the supplied flat-cartoon pet image into highly simplified low-resolution pixel art.",
  "",
  "The supplied image is already the approved visual design.",
  "",
  "Do NOT reinterpret or redesign the pet. Your task is only to translate the existing design into a coarse, consistent pixel-art representation suitable for automatic grid recovery.",
  "",
  "SOURCE FIDELITY",
  "",
  "Treat the flat-cartoon image as the authoritative source.",
  "",
  "Preserve its:",
  "",
  "head silhouette and proportions",
  "ear shape, size, spacing, and position",
  "eye size, spacing, position, shape, and color",
  "nose and muzzle proportions",
  "major color regions and markings",
  "meaningful asymmetry",
  "relative positions of important features",
  "",
  "Do not invent, remove, beautify, rearrange, or symmetrize important features.",
  "",
  "Pixelation may simplify boundaries, but must not change the semantic structure.",
  "",
  "Convert the existing design into pixels rather than designing a new pet.",
  "",
  "SINGLE GLOBAL PIXEL SCALE",
  "",
  "The entire image must visually follow one single, uniform square-pixel grid.",
  "",
  "Use the same apparent pixel-block size for the silhouette, ears, eyes, nose, markings, thin features, and background boundary.",
  "",
  "Do not use smaller pixels for detailed areas.",
  "",
  "Do not mix pixel scales or create micro-pixels inside larger regions.",
  "",
  "Target approximately 32–40 visual grid cells along the pet's longest occupied dimension.",
  "",
  "Prefer large, chunky, clearly visible square pixel blocks.",
  "",
  "PIXELIZATION",
  "",
  "Translate smooth curves and diagonals into simple coarse staircase boundaries.",
  "",
  "Keep major shapes stable, connected, and close to the source.",
  "",
  "Prefer large connected color clusters over fragmented regions.",
  "",
  "Avoid:",
  "",
  "isolated pixel noise",
  "unnecessary tiny islands",
  "dithering",
  "checkerboard patterns",
  "irregular high-frequency edges",
  "anti-aliasing",
  "sub-grid details",
  "",
  "If a detail cannot be represented at the global pixel scale, simplify or remove secondary detail rather than introducing smaller pixels.",
  "",
  "IDENTITY PRIORITY",
  "",
  "When simplification is necessary, preserve first:",
  "",
  "head and ear geometry",
  "eye size, spacing, position, and color",
  "major facial color distribution",
  "distinctive large markings",
  "important eye-surrounding or central facial features",
  "nose and muzzle structure",
  "",
  "Remove secondary details before changing these identity-defining features.",
  "",
  "If the source intentionally contains thickened identity features, preserve their thickness during pixelization.",
  "",
  "COLOR",
  "",
  "Preserve the source image's semantic colors.",
  "",
  "Use solid flat colors only.",
  "",
  "Do not introduce new colors for shading, lighting, texture, depth, anti-aliasing, or edge smoothing.",
  "",
  "If several very similar source colors represent the same region, they may be merged into one representative color.",
  "",
  "Prefer approximately 5–8 major subject colors when possible.",
  "",
  "Preserve distinctive colors even when they occupy a smaller region.",
  "",
  "Pixelization may change region boundaries and resolution only. Preserve each major region's hue, lightness, saturation, and warm/cool balance from the approved flat-cartoon image.",
  "",
  "Keep small but identity-defining color regions, including eye color, nose color, and distinctive markings, as separate pixel clusters when they are visible in the source.",
  "",
  "Do not replace distinct colors with gray or beige, and do not globally boost saturation.",
  "",
  "Absolutely no gradients, soft transitions, transparency, or color blending.",
  "",
  "FACIAL AND THIN FEATURES",
  "",
  "Keep eyes faithful to the source using a few large pixel clusters.",
  "",
  "Preserve a simple eye highlight if it is clearly present in the source and large enough to survive the target scale.",
  "",
  "Do not add fine iris detail.",
  "",
  "Represent important thin features using the same global pixel scale.",
  "",
  "If a whisker or thin feature cannot be represented without using smaller pixels, simplify or omit it.",
  "",
  "BACKGROUND AND OUTLINE",
  "",
  "Preserve one completely uniform solid technical background color.",
  "",
  "Do not add texture, gradients, noise, shadows, or decoration.",
  "",
  "Do not add a new artificial outer outline.",
  "",
  "GRID-RECOVERY COMPATIBILITY",
  "",
  "The output will be processed by an algorithm that detects one dominant global pixel grid.",
  "",
  "Therefore, prioritize:",
  "",
  "one consistent square pixel-block scale",
  "clear staircase boundaries",
  "large connected color regions",
  "low visual complexity",
  "one dominant spatial pixel rhythm",
  "",
  "Avoid mixed pixel sizes, anti-aliasing, micro-details, dithering, high-frequency texture, and visible grid lines.",
  "",
  "OUTPUT",
  "",
  "Produce a coarse pixel-art translation of the supplied flat-cartoon image.",
  "",
  "Prioritize:",
  "",
  "SOURCE FIDELITY",
  "IDENTITY PRESERVATION",
  "ONE GLOBAL PIXEL SCALE",
  "LARGE CONNECTED COLOR REGIONS",
  "",
  "Do not add details or redesign the pet.",
  "",
  "Convert the existing design into pixels — nothing more.",
].join("\n");

export const generationStyles: GenerationStyleConfig[] = [
  {
    id: "pet-avatar",
    label: "宠物头像",
    maxColors: 20,
    stages: [
      { id: "flat-cartoon", label: "生成扁平卡通画", prompt: flatCartoonPrompt },
      { id: "pixel-art", label: "像素风格化", prompt: pixelArtPrompt },
    ],
  },
];

export function buildGenerationPromptStages(
  style: AiGenerationStyle,
): ResolvedGenerationPromptStage[] {
  const config = generationStyles.find((item) => item.id === style);
  if (!config) {
    throw new Error("不支持的生成风格：" + style);
  }
  return config.stages.map((stage) => ({ id: stage.id, label: stage.label, prompt: stage.prompt() }));
}

/** Returns all stages for diagnostics and backwards-compatible prompt inspection. */
export function buildGenerationPrompt(
  style: AiGenerationStyle,
): string {
  return buildGenerationPromptStages(style)
    .map((stage, index) => "Stage " + (index + 1) + ": " + stage.label + "\n" + stage.prompt)
    .join("\n\n");
}
